mysite/mysite/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf import settings 
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views
from accounts.views import signup # import views as accounts_views
from accounts import views as accounts_views
from boards.views import (
	new_topic,
	reply_topic,
	)
from boards import views


urlpatterns = [
	url(r'^settings/account/$', accounts_views.UserUpdateView.as_view(), name='my_account'),	
	url(r'^boards/$', views.BoardListView.as_view(), name='board'),
    url(r'^boards/(?P<pk>\d+)/$', views.TopicListView.as_view(), name='board_topics'),
    url(r'^boards/(?P<pk>\d+)/new/$', views.new_topic, name='new_topic'),
    url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/$', views.PostListView.as_view(), name='topic_posts'),
    url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/reply/$', views.reply_topic, name='reply_topic'),
    url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/posts/(?P<post_pk>\d+)/edit/$',
        views.PostUpdateView.as_view(), name='edit_post'),

	url(r'^login/$',
		 auth_views.login, 
		 name='login'),
	url(r'^logout/$',
		 auth_views.logout,
		 name='logout'),
	url(r'^admin/', 
			admin.site.urls),
	url(r'^signup/$', 
		signup, 
		name='signup'), # or from accounts import views  as accounts_views and in url add accounts_views.signup , signup is name of out view

	url(r'^', include('posts.urls', namespace='posts')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 







	











    

mysite/posts/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from posts.views import (
	listofposts,
	create_post,
	detail,
	update_post,
	category,
	)

urlpatterns = [
	url(r'^create/', 
		create_post ,
		name='create_post'),
	url(r'^category/(?P<slug>[-\w]+)/$',
		category,
		name='category'),
	url(r'^(?P<slug>[-\w]+)/edit/$',
		update_post,
		name = 'update_post'),
	url(r'^(?P<slug>[-\w]+)/$',
		detail,
		name = 'detail'),
	url(r'^$',
		listofposts ,
		name='listofposts'),
]

mysite/boards/models.py
# from django.contrib.auth.models import User
# import markdown
from accounts.models import User
from django.db import models
from django.utils.text import Truncator
from django.utils.html import mark_safe
from markdown import markdown


class Board(models.Model):
    name = models.CharField(max_length=30, unique=True)
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def get_posts_count(self):
        return Post.objects.filter(topic__board=self).count()

    def get_last_post(self):
        return Post.objects.filter(topic__board=self).order_by('-created_at').first()


class Topic(models.Model):
    board = models.ForeignKey(Board, related_name='topics')
    starter = models.ForeignKey(User, related_name='topics')
    subject = models.CharField(max_length=255)
    last_updated = models.DateTimeField(auto_now_add=True)
    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.subject


class Post(models.Model):
    topic = models.ForeignKey(Topic, related_name='posts')
    message = models.TextField(max_length=4000)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)
    created_by = models.ForeignKey(User, related_name='posts')
    updated_by = models.ForeignKey(User, null=True, related_name='+')

    def __str__(self):
        truncated_message = Truncator(self.message)
        return truncated_message.chars(30)

    def get_message_as_markdown(self):
        return mark_safe(markdown(self.message, safe_mode='escape'))

mysite/posts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User



def upload_location(instance, filename):
	return "%s/%s" %(instance.id, filename)	

class Category(models.Model):
	name = models.CharField(max_length=20)
	slug = models.SlugField(max_length=200, unique=True	)

	class Meta:
		ordering = ['name']
		verbose_name = 'Категория'
		verbose_name_plural = 'Категории'

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('posts:category', args=[str(self.slug)]) 


class Post(models.Model):
	title = models.CharField(max_length = 100) 
	content = models.TextField(
		max_length = 600, default = 'cool' 
		)
	date_of_creating = models.DateTimeField(
		auto_now=False, auto_now_add=True
		)
	image = models.ImageField(
		upload_to=upload_location,
		null=True, 
		blank=True, 
		height_field="height_field", 
		width_field="width_field"
		)
	height_field = models.IntegerField(default=0)
	width_field = models.IntegerField(default=0) 
	category = models.ForeignKey('Category')
	slug = models.SlugField(unique=True, blank=False)

	class Meta:
		ordering = ['title']
		verbose_name = 'Пост'
		verbose_name_plural = 'Посты'
		index_together = [
		['id', 'slug']
		]	 


	def __str__(self):
		return self.title


	def get_absolute_url(self):
		return reverse('posts:detail',
						 args=[str(self.slug)]
						 ) 
		# Или так например
		# kwargs={'slug': self.slug})

mysite/boards/forms.py
from django import forms
from boards.models import Topic, Post


class NewTopicForm(forms.ModelForm):
    message = forms.CharField(
    widget=forms.Textarea(
    attrs={'rows': 5, 'placeholder': 'Message'}
    ),
    max_length=4000,
    help_text='The max length of the text is 4000.'
    )

    class Meta:
        model = Topic
        fields = ['subject', 'message']


    def __str__(self):
        return self.message

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['message', ]

mysite/posts/forms.py
# -*- coding: utf-8 -*-
from django import forms
from posts.models import Post , Category
from pagedown.widgets import PagedownWidget
from django.contrib.auth.models import User

class PostForm(forms.ModelForm):
	content = forms.CharField(widget= PagedownWidget(show_preview=False))
	def __init__(self, *args, **kwargs):
		super(PostForm, self).__init__(*args, **kwargs)
		self.fields['content'].widget.attrs.update({'class': 'XXXXX'})
	class Meta:
		model = Post
		fields = [
			"title",
			"content",
			"image",
			'category',
			'slug',
			]

mysite/boards/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from accounts.models import User
from django.shortcuts import render
from .models import Board
from django.shortcuts import render, redirect, get_object_or_404
from boards.forms import NewTopicForm, PostForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from boards.models import Board, Post, Topic
from django.db.models import Count
from django.shortcuts import redirect
from django.views.generic import UpdateView
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import ListView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from posts.views import listofposts

# GCBV
class BoardListView(ListView):
	model = Board
	context_object_name = 'boards'
	template_name = 'boards.html'


class TopicListView(ListView):
	model = Topic
	context_object_name = 'topics'
	template_name = 'topics.html'
	paginate_by = 10

	# board is the field in models.py
	def get_context_data(self, **kwargs):
		kwargs['board'] = self.board
		return super(TopicListView, self).get_context_data(**kwargs)

	def get_queryset(self):
		self.board = get_object_or_404(Board, pk=self.kwargs.get('pk'))
		queryset = self.board.topics.order_by('-last_updated').annotate(replies=Count('posts') - 1)
		return queryset


@login_required
def new_topic(request, pk):
	board = get_object_or_404(Board, pk=pk)
	user = User.objects.first()  # TODO: get the currently logged in user
	if request.method == 'POST':
		form = NewTopicForm(request.POST)
		if form.is_valid():
			topic = form.save(commit=False)
			topic.board = board
			topic.starter = user
			topic.save()
			post = Post.objects.create(
			message=form.cleaned_data.get('message'),
			topic=topic,
			created_by=user
			)
		return redirect('board_topics', pk=board.pk)  # TODO: redirect to the created topic page
	else:
		form = NewTopicForm()
	return render(request, 'new_topic.html', {'board': board, 'form': form})


@login_required
def reply_topic(request, pk, topic_pk):
	topic = get_object_or_404(Topic, board__pk=pk, pk=topic_pk)
	if request.method == 'POST':
		form = PostForm(request.POST)
		if form.is_valid():
			post = form.save(commit=False)
			post.topic = topic
			post.created_by = request.user
			post.save()
			return redirect('topic_posts', pk=pk, topic_pk=topic_pk)
	else:
		form = PostForm()
	return render(request, 'reply_topic.html', {'topic': topic, 'form': form})


class PostListView(ListView):
	model = Post
	context_object_name = 'posts'
	template_name = 'topic_posts.html'
	paginate_by = 2

	def get_context_data(self, **kwargs):
		self.topic.views += 1
		self.topic.save()
		kwargs['topic'] = self.topic
		return super(PostListView, self).get_context_data(**kwargs)

	# Here we define query to url
	def get_queryset(self):
		self.topic = get_object_or_404(Topic, board__pk=self.kwargs.get('pk'), pk=self.kwargs.get('topic_pk'))
		queryset = self.topic.posts.order_by('created_at')
		return queryset





@method_decorator(login_required, name='dispatch')
class PostUpdateView(UpdateView):
	model = Post
	fields = ('message', )
	template_name = 'edit_post.html'
	pk_url_kwarg = 'post_pk'
	context_object_name = 'post'

# With the line queryset = super().get_queryset() 
# we are reusing the get_queryset method from 
# the parent class, that is, the UpateView class.
# Then, we are adding an extra filter to the queryset,
# which is filtering the post using the logged in user,
# available inside the request object.

	def get_queryset(self):
		queryset = super(PostUpdateView, self).get_queryset()
		return queryset.filter(created_by=self.request.user)

	def form_valid(self, form):
		post = form.save(commit=False)
		post.updated_by = self.request.user
		post.updated_at = timezone.now()
		post.save()
		return redirect('topic_posts', pk=post.topic.board.pk, topic_pk=post.topic.pk)

mysite/templates/base.html
{% load staticfiles %}
{% include "messages_display.html" %}
{% include "head.html" %}
{% block extra %}
{% endblock extra %}
<!DOCTYPE html>
<html class="no-js"> 
<head>
<title>{% block block_title %}Programming{% endblock block_title %}</title>
<meta charset="utf-8">
</head>
<body>
<div class="content">


<div class="box-wrap ">
	<header role="banner" id="fh5co-header">
		<div class="container ">
			<nav class="navbar navbar-default">
			
					<div class="col-md-4">
						<div id="navigator">
							<ul id="nav">
								<li class="nav_tab">
								{% for x in list %}
								<a href="{{ x.get_absolute_url }}"><p>{{ x.title }}</p></a>
								{% endfor %}
								</li>
							</ul>
						</div>
						<div class="menu-icon animate-box">			
						<div class="line_one"></div>
						<div class="line_two"></div>
						<div class="line_three"></div>  			
						</div>
					</div>
					<div class="col-md-4">
						<div class="fh5co-navbar-brand">
						<a href='/'><p>-PROGRAMMING- -AND OTHER-</p></a>
						</div>
					</div>
					

				
					
				<div class="col-md-4 animate-box">
						<ul class="social">

							<li><a href="https://github.com/IvanChernoborodov"><i class="fa fa-github" aria-hidden="true"></i>
							</a></li>
							<li><a href="https://t.me/ivanChb"><i class="fa fa-telegram" aria-hidden="true"></i>
							</a></li>
							{% if user.is_authenticated %}
								Hi {{ user.username }}!
								<a href="{% url 'my_account' %}" }">Аккаунт</a>
								<a href="{% url 'logout' %}">logout</a>
							{% else %}
								<a href="{% url 'login' %}">login</a>

								<a href="{% url 'signup' %}">Sign up</a>
							{% endif %}
								<a href="{% url 'board' %}">Обсуждения</a>


							
						</ul>
					</div>
			</nav>
			<div class="col-lg-6 col-lg-offset-3 animate-box">
				<form method="GET" action='' >
					<div class="search-bar">
						<input type="text" name='q' placeholder="search" value='{{ request.get.q }}' required=""></input>
						<div class="search-icon"></div>
					</div>
				</form>
			</div>
		</div>
		<section id="intro">
			<nav class='menu animate-box'>
				<div class="wideDiv">
				{% block category %}
				{% for c in category_all %}
				<a href="{{ c.get_absolute_url }}">{{ c.slug }}</a>
				{% endfor %}
				{% endblock category %}
				</div>
			</nav>
		</section>
	</header>
{% block body %}
{% endblock body %}
<main>
{%  block content %}
	<section id="work">
		<div class="container">
			<div class="row">
				{% for x in list %}
					<div class="col-md-4">
						{% if x.image %}
						<div class="fh5co-grid animate-box" style="background-image: url({{ x.image.url }});">
							<a class="image-popup text-center" href="{{ x.get_absolute_url }}">
								<div class="work-title">
									<h3>{{ x.title }}</h3>
									<span>{{ x.category }}</span>
								</div>
							</a>
						</div>
						{% endif %}
					</div>
				{% endfor %}
			</div>
		</div>
	</section>
{% endblock content %}
</main>


{% block footer %}
	<footer id="footer" role="contentinfo">
		<div class="container">
			<div class="row">
				<div class="col-md-12 text-center ">
					<div class="footer-widget border">

						<p class=""><small>PYTHON 3.6</small><br></p>
						<small class='django'>Django 1.11</small>
					</div>
				</div>
			</div>
		</div>
	</footer>
{% endblock footer %}
</body>
</html>

mysite/templates/base_boards.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Обсуждения{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  </head>

{% block body %}
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <div class="container">
   
    <a class="navbar-brand" href="{% url 'posts:listofposts' %}">Главная</a>
    <a class="navbar-brand" href="{% url 'board' %}">Обсуждения</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="mainMenu">
      {% if user.is_authenticated %}
        <ul class="navbar-nav ml-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{ user.username }}
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
              <a class="dropdown-item" href="{% url 'my_account' %}" }">Аккаунт</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
            </div>
          </li>
        </ul>
      {% else %}
        <form class="form-inline ml-auto">
          <a href="{% url 'login' %}" class="btn btn-outline-secondary">Log in</a>
          <a href="{% url 'signup' %}" class="btn btn-primary ml-2">Sign up</a>
        </form>
      {% endif %}
    </div>
  </div>
</nav>
  <div class="container">
    <ol class="breadcrumb my-4">
      {% block breadcrumb %}
      {% endblock %}
    </ol>
    {% block content %}
    {% endblock %}
  </div>
{% endblock body %}


<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
 {% block javascript %}{% endblock %}  <!-- Add this empty block here! -->
</html>

mysite/templates/category.html
{% extends "base.html" %}
{% block content %}
<section id="work">
    <div class="container">
        <div class="row">
            {% for p in post %}
                <div class="col-md-4">
                    {% if p.image %}
                        <div class="fh5co-grid animate-box" style="background-image: url({{ p.image.url }});">
                            <a class="image-popup text-center" href="{{ p.get_absolute_url }}">
                                <div class="work-title">
                                    <h3>{{ p.title }}</h3>
                                    <span>{{ p.category }}</span>
                                </div>
                            </a>
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}




 

mysite/templates/create_post.html
{% extends "base.html" %}
{% block block_title %}
Edit|{{ instance.title }}
{% endblock block_title %}
{% block extra %}
{{ form.media }}
{% endblock extra %}

{% block content %}
	<div class="col-md-6 ">
		<form method='POST' action='' enctype="multipart/form-data">{% csrf_token %}
			{{ form.as_p }}
			<input type='submit' value="Create Post">
		</form>
	</div>
	<div class="col-md-6" >
		<div class="content-preview" ></div>
		<h3 id="preview-title"></h3>
		<p id="preview-content"></p>	
		<p id="preview-slug" ></p>
	</div>	
{% endblock %}

{% block footer %}
{% endblock %}

mysite/templates/edit_post.html
{% extends 'base_boards.html' %}

{% block title %}Edit post{% endblock %}


{% block javascript %}

  <script>
    var simplemde = new SimpleMDE();
  </script>
{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'board' %}">Boards</a></li>
  <li class="breadcrumb-item"><a href="{% url 'board_topics' post.topic.board.pk %}">{{ post.topic.board.name }}</a></li>
  <li class="breadcrumb-item"><a href="{% url 'topic_posts' post.topic.board.pk post.topic.pk %}">{{ post.topic.subject }}</a></li>
  <li class="breadcrumb-item active">Edit post</li>
{% endblock %}

{% block content %}
  <form method="post" class="mb-4" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Save changes</button>
    <a href="{% url 'topic_posts' post.topic.board.pk post.topic.pk %}" class="btn btn-outline-secondary" role="button">Cancel</a>
  </form>
{% endblock %}

mysite/templates/head.html
{% load staticfiles %}
<script src="https://code.jquery.com/jquery-1.10.1.min.js"></script>
<script type="text/javascript">
	$(document).ready(function () {

    $('.menu-icon').click(function () {
        if ($('#navigator').css("left") == "-250px") {
            $('#navigator').animate({left: '0px'}, 350);
            $('.menu-icon').animate({left: '250px'}, 350);
            $('.menu-text').animate({left: '300px'}, 350).empty().text("Close");
        } 
        else  {
            $('#navigator').animate({left: '-250px'}, 350); 
            $(this).animate({left: '0px'}, 350);
            $('.menu-text').animate({left: '50px'}, 350).empty().text("Menu");

        } 
	});
    $('.menu-icon').click(function () {
	            $(this).toggleClass("on"); });
});
</script>
<script
	src="https://code.jquery.com/jquery-2.2.4.min.js"
	integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
	crossorigin="anonymous">
</script>
<script type="text/javascript">
	$(document).ready(function(){
			$(".content-markdown").each(function(){
				var content =  $(this).text()
				var markedContent = marked(content)
				console.log(markedContent)
				$(this).html(markedContent)
		})
			// script for responsive imgs of class "content-markdown"
			$(".content-markdown img").each(function(){
				$(this).addClass("img-responsive");
		})
			var titleItem = $('#id_title')
			$("#preview-title").text(titleItem.val())
			var contentItem = $('#id_content')
			$("#preview-content").html(marked(contentItem.val()))
	 		function CutTheImage(value){
				var markedContent = marked(value)
				$("#preview-content").html(markedContent)
				$("#preview-content img").each(function(){
					$(this).addClass("img-responsive")

				})		
			}
			CutTheImage(contentItem.val( ))
			contentItem.keyup(function(){
				var newContent = $(this).val()
				CutTheImage(newContent)
			})
			function PrevTitle(value){
				$("#preview-title").text(value)
			}
			PrevTitle(titleItem.val())
			titleItem.keyup(function(){
				var newTitle = $(this).val()
				PrevTitle(newTitle)

			})
			function PrevSlug(value){
				$('#id_slug').html(value)
			}
			PrevSlug(titleItem.val())
			titleItem.keyup(function(){
				var newSlug = $(this).val()
				PrevSlug(newSlug)
			})
	})
</script>
<!--========================SCRIPTS================================== -->
<script src='{% static "js/modernizr-2.6.2.min.js" %}'></script>
<!-- jQuery -->
<script src='{% static "js/jquery.min.js" %}'></script>
<!-- jQuery Easing -->
<!-- <script src='{% static "js/jquery.easing.1.3.js" %}'></script> -->
<!-- Bootstrap -->
<script src='{% static "js/bootstrap.min.js" %}'></script>
<!-- Waypoints -->
<script src= '{% static "js/jquery.waypoints.min.js" %}'></script>
<!-- Main JS (Do not remove) -->
<script src='{% static "js/main.js" %}'></script> 
<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.6/marked.min.js"
</script>
<link rel="shortcut icon" href="favicon.ico">
<script src='{% static "js/jquery.waypoints.min.js" %}'></script>
<!-- =============================FONTS============================== -->
<link href="https://fonts.googleapis.com/css?family=Mrs+Sheppards" rel="stylesheet"> 
<link href="https://fonts.googleapis.com/css?family=Holtwood+One+SC|Marcellus+SC|Volkhov" rel="stylesheet"> 	
<link href="https://fonts.googleapis.com/css?family=Playfair+Display" rel="stylesheet"> 
<link href="https://fonts.googleapis.com/css?family=Rock+Salt" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Monoton" rel="stylesheet"> 
<link href="https://fonts.googleapis.com/css?family=Monoton|Press+Start+2P" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Cuprum|PT+Sans+Narrow|Playfair+Display+SC" rel="stylesheet"> 
<link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,300,700|Roboto:300,400' rel='stylesheet' type='text/css'>
<!-- ==============================CSS=============================== -->
<link rel="stylesheet" href='https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'>
<!-- Animate.css -->
<link rel="stylesheet" href='{% static "css/animate.css" %}'>
<!-- Bootstrap  -->
<link rel="stylesheet" href='{% static "css/bootstrap.css" %}'>
<link rel="stylesheet" href='{% static "css/base.css" %}'>

mysite/templates/markdown.html
<script src="https://code.jquery.com/jquery-1.10.1.min.js"></script>
<script type="text/javascript">
	$(document).ready(function () {
    $('.menu-icon').click(function () {
        if ($('#navigator').css("left") == "-250px") {
            $('#navigator').animate({left: '0px'}, 350);
            $('.menu-icon').animate({left: '250px'}, 350);
            $('.menu-text').animate({left: '300px'}, 350).empty().text("Close");
        } 
        else  {
            $('#navigator').animate({left: '-250px'}, 350); 
            $(this).animate({left: '0px'}, 350);
            $('.menu-text').animate({left: '50px'}, 350).empty().text("Menu");

        } 
	});
    $('.menu-icon').click(function () {
	            $(this).toggleClass("on"); });
});
</script>
<script
	src="https://code.jquery.com/jquery-2.2.4.min.js"
	integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
	crossorigin="anonymous">
</script>
<script type="text/javascript">
	$(document).ready(function(){
			$(".content-markdown").each(function(){
				var content =  $(this).text()
				var markedContent = marked(content)
				console.log(markedContent)
				$(this).html(markedContent)
		})
			// script for responsive imgs of class "content-markdown"
			$(".content-markdown img").each(function(){
				$(this).addClass("img-responsive");
		})
			var titleItem = $('#id_title')
			$("#preview-title").text(titleItem.val())
			var contentItem = $('#id_content')
			$("#preview-content").html(marked(contentItem.val()))
	 		function CutTheImage(value){
				var markedContent = marked(value)
				$("#preview-content").html(markedContent)
				$("#preview-content img").each(function(){
					$(this).addClass("img-responsive")

				})		
			}
			CutTheImage(contentItem.val( ))
			contentItem.keyup(function(){
				var newContent = $(this).val()
				CutTheImage(newContent)
			})
			function PrevTitle(value){
				$("#preview-title").text(value)
			}
			PrevTitle(titleItem.val())
			titleItem.keyup(function(){
				var newTitle = $(this).val()
				PrevTitle(newTitle)

			})
			function PrevSlug(value){
				$('#id_slug').html(value)
			}
			PrevSlug(titleItem.val())
			titleItem.keyup(function(){
				var newSlug = $(this).val()
				PrevSlug(newSlug)
			})
	})
</script>

mysite/templates/messages_display.html
{% if messages %}
<div class = "messages">
	<ul class="messages">
	{% for message in messages %}
	<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
	{% endfor %}
	</ul>
</div>
{% endif %}

mysite/templates/my_account.html
{% extends 'base_boards.html' %}

{% block title %}My account{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">My account</li>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <form enctype="multipart/form-data" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Save changes</button>
      </form>
    </div>
  </div>
{% endblock %}

mysite/templates/new_topic.html
{% extends 'base_boards.html' %}

{% block title %}Добавить новую ветку{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'board' %}">Обсуждение</a></li>
  <li class="breadcrumb-item"><a href="{% url 'board_topics' board.pk %}">{{ board.name }}</a></li>
  <li class="breadcrumb-item active">Новое обсуждение</li>
{% endblock %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Post</button>
  </form>
{% endblock %}